import json
import base64
import cv2
import numpy as np
import os
from dotenv import load_dotenv
from typing import List, Dict, Any, Optional
from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from huggingface_hub import InferenceClient

# Hot-reload the environment variables dynamically
load_dotenv(override=True)

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# You can configure the HF API Key in a .env file: HF_API_KEY=your_token_here
hf_token = os.getenv("HF_API_KEY")

# VLM model robust for OCR and OMR layouts
MODEL_ID = "Qwen/Qwen2.5-VL-7B-Instruct"
client = InferenceClient(MODEL_ID, token=hf_token)

def compress_image_for_api(image_bytes: bytes) -> str:
    """Downscales the image to ensure it fits comfortably in HuggingFace free tier payloads."""
    np_arr = np.frombuffer(image_bytes, np.uint8)
    img = cv2.imdecode(np_arr, cv2.IMREAD_COLOR)
    
    if img is None:
        raise ValueError("Invalid image uploaded.")
        
    h, w = img.shape[:2]
    max_dim = 1200
    if max(h, w) > max_dim:
        scale = max_dim / max(h, w)
        img = cv2.resize(img, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)
        
    _, buffer = cv2.imencode('.jpg', img, [cv2.IMWRITE_JPEG_QUALITY, 85])
    return base64.b64encode(buffer).decode("utf-8")

def process_omr_image(image_bytes: bytes, answer_key: Dict[int, int]) -> Dict[str, Any]:
    # 1. Compress and encode image for the API
    encoded_img = compress_image_for_api(image_bytes)
    img_url = f"data:image/jpeg;base64,{encoded_img}"

    # 2. Craft exact VLM Prompt
    prompt = """
You are a highly precise Optical Mark Recognition (OMR) scanner. 
I am providing you an image of an OMR answer sheet containing multiple columns of questions. 
Your task is to identify the filled answer for each question perfectly. 

Output your findings STRICTLY as a JSON object where the keys are the continuous Question Numbers (starting from 1, e.g. "1", "2", "3"...) and the values are integers mapping to the filled option (0 for A, 1 for B, 2 for C, 3 for D). 
- If multiple bubbles are filled for a single question, output -1.
- If no bubbles are filled, output null.

Example format:
{
  "1": 0,
  "2": 1,
  "3": 3,
  "4": -1,
  "5": null
}

Do NOT output any markdown tags. Output ONLY the raw JSON string parsing all visible questions on the page.
"""
    
    try:
        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image_url", "image_url": {"url": img_url}},
                    {"type": "text", "text": prompt},
                ],
            }
        ]
        
        # Fire request to Hugging Face Free Inference API
        response = client.chat_completion(messages=messages, max_tokens=2500)
        raw_output = response.choices[0].message.content.strip()
        
        # Strip potential markdown formatting that VLMs sometimes append
        if "```" in raw_output:
             raw_output = raw_output.split("```")[1]
             if raw_output.startswith("json"):
                 raw_output = raw_output[4:].strip()
            
        detected_answers = json.loads(raw_output)
        
    except Exception as e:
        err_msg = str(e)
        if "Authorization header is correct" in err_msg or "401" in err_msg:
             raise Exception("Hugging Face API Authentication failed! Please add your HF_API_KEY to the backend/.env file.")
        raise Exception(f"Hugging Face Vision API Error: {err_msg}")

    # 3. Grade the parsed JSON against the Teacher's Answer Key
    score = 0
    results = []
    
    # Dynamic range to capture everything generated by the VLM
    max_questions = max(len(answer_key), len(detected_answers)) if answer_key else len(detected_answers)
    
    for q_idx in range(max_questions):
        question_num = q_idx + 1 # 1-indexed UI mapping
        
        expected_ans = answer_key.get(q_idx)
        
        # Ensure we check string representation since JSON keys are strings
        bubbled_val = detected_answers.get(str(question_num), None)
        
        if bubbled_val is not None:
            try:
                bubbled = int(bubbled_val)
            except ValueError:
                bubbled = None
        else:
            bubbled = None
            
        correct = False
        if bubbled is not None and bubbled != -1 and expected_ans == bubbled:
            correct = True
            score += 1

        results.append({
            "question_num": question_num,
            "selected_option": bubbled,
            "correct_option": expected_ans,
            "is_correct": correct,
            "is_multiple": bubbled == -1
        })

    max_score = len(answer_key) if answer_key and len(answer_key) > 0 else max_questions
    
    return {
        "score": score,
        "max_score": max_score,
        "results": results
    }

def parse_csv_to_dict(csv_bytes: bytes) -> Dict[int, int]:
    # Dynamic CSV parsing handling Option characters A/B/C/D into integers 0/1/2/3
    lines = csv_bytes.decode("utf-8").splitlines()
    answer_key = {}
    
    for line in lines:
        if not line.strip() or "," not in line:
            continue
        parts = line.split(",")
        try:
            # 1-indexed to 0-indexed internal standard
            q_num = int(parts[0].strip()) - 1 
            ans_str = parts[1].strip().upper()
            
            # Map A->0, B->1, C->2, D->3
            if ans_str == "A": ans_idx = 0
            elif ans_str == "B": ans_idx = 1
            elif ans_str == "C": ans_idx = 2
            elif ans_str == "D": ans_idx = 3
            else: ans_idx = int(ans_str) 
                
            answer_key[q_num] = ans_idx
        except ValueError:
            pass # Skip invalid rows
            
    return answer_key

@app.post("/grade-omr-bulk/")
async def grade_omr_bulk(
    images: List[UploadFile] = File(...),
    answer_key_csv: Optional[UploadFile] = File(None),
    answer_key_json: Optional[str] = Form(None)
):
    """
    Accepts:
    1. A CSV file OR a JSON string containing the master answer key
    2. A list of image files (students' OMR sheets)
    Returns Hugging Face verified grading scores metrics.
    """
    
    answer_key = None
    
    try:
        if answer_key_csv:
            csv_bytes = await answer_key_csv.read()
            answer_key = parse_csv_to_dict(csv_bytes)
        elif answer_key_json:
            raw_dict = json.loads(answer_key_json)
            # Ensure keys and values are correctly converted to ints
            answer_key = {int(k): int(v) for k, v in raw_dict.items()}
            
        if not answer_key:
             raise HTTPException(status_code=400, detail="Missing or invalid Answer Key (CSV or JSON)")
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Failed to parse Answer Key Context: {str(e)}")

    batch_results = []
    
    for image in images:
        try:
            img_bytes = await image.read()
            student_result = process_omr_image(img_bytes, answer_key)
            batch_results.append({
                "filename": image.filename,
                "success": True,
                "data": student_result
            })
        except Exception as e:
            batch_results.append({
                "filename": image.filename,
                "success": False,
                "error": str(e)
            })
            
    return {"batch_results": batch_results}
